spring:
  datasource:
    url: ${DFC_POSTGRES_DB_URL}
    username: ${DFC_POSTGRES_USERNAME}
    password: ${DFC_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  open-ai:
    api-key: ${DFC_OPEN_AI_KEY}